redirect:
  /voltage-modular-user-guide: /
  /cherry-audio: /cherry-audio/modules/additive-oscillator
  /cherry-audio/modules: /cherry-audio/modules/additive-oscillator
  /misfit-audio: /misfit-audio/modules/drum-trigger-sequencer
  /misfit-audio/modules: /misfit-audio/modules/drum-trigger-sequencer
  /voltage-modular-user-guide/IO-panel: /voltage-modular-user-guide/io-panel
  /modules/minilfo: /cherry-audio/modules/mini-lfo
  /modules/noise-generator: /cherry-audio/modules/noise-generator
  /cherry-audio/modules/noise_generator: /cherry-audio/modules/noise-generator
